# This file was generated by GoReleaser. DO NOT EDIT.
cask "damstack" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/damstack"]
    end
  end

  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "4ed6eefbe416b9538b1106bd100e4a040023689fc3ce335bf940de423014f111"
      url "https://github.com/eugene-panin/damstack/releases/download/v#{version}/damstack_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "efe4123364b444290141571bafd1af3c3528c1f7bd81ea5e52f0c2260f556b6a"
      url "https://github.com/eugene-panin/damstack/releases/download/v#{version}/damstack_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "damstack"
  desc "Set up your own server and run apps on it from one file you edit"
  homepage "https://github.com/eugene-panin/damstack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "damstack"

  # No zap stanza required

  caveats <<~EOS
    Run damstack: it checks this Mac and says where to start.
  EOS
end
