# This file was generated by GoReleaser. DO NOT EDIT.
cask "damstack" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "e4c4473cfc16e19400dc43e6f7d8bed24d965d05c7f53550e7fedd2ac2761d78"
      url "https://github.com/eugene-panin/damstack/releases/download/v#{version}/damstack_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd7ee95fca1f9f5ddcd6e826c94401eddc6c9eff04defee0402928b86adc05fd"
      url "https://github.com/eugene-panin/damstack/releases/download/v#{version}/damstack_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ae8e11470b8d1b0fd9742995cb2367534711fdcfe5478d34fb74256435cbfddf"
      url "https://github.com/eugene-panin/damstack/releases/download/v#{version}/damstack_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f518453520321ca0d644c2a1b976539cd7e09b332097145c87ec7830310762fb"
      url "https://github.com/eugene-panin/damstack/releases/download/v#{version}/damstack_#{version}_linux_amd64.tar.gz"
    end
  end

  name "damstack"
  desc "Set up your own server and run apps on it, from one file you edit, with nothing but Docker installed"
  homepage "https://github.com/eugene-panin/damstack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "damstack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/damstack"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    damstack runs its tools in Docker: install Docker Desktop, OrbStack or Colima.
    Then run damstack: it checks this machine and says where to start.
  EOS
end
