# This file was generated by GoReleaser. DO NOT EDIT.
cask "damstack" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/damstack"]
    end
  end

  version "0.2.6"

  on_macos do
    on_arm do
      sha256 "3e98832dfe3446884945256c7c01f8519f113bf836cf45980999dfae24c19b84"
      url "https://github.com/eugene-panin/damstack/releases/download/v#{version}/damstack_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4654ce6ea7b09c9f2d7cbf0a7fc248147ce36c34d41bf8b915fbe4ef6c939c7b"
      url "https://github.com/eugene-panin/damstack/releases/download/v#{version}/damstack_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "damstack"
  desc "Set up your own server and run apps on it from one file you edit"
  homepage "https://github.com/eugene-panin/damstack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "damstack"

  # No zap stanza required

  caveats <<~EOS
    Run damstack: it checks this Mac and says where to start.
  EOS
end
