# This file was generated by GoReleaser. DO NOT EDIT.
cask "kx" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "a9b37a5e40308effb11792f5b448b1ac9a89ea1ff57eb18bacea08b2aed80193"
      url "https://github.com/eugene-panin/kx/releases/download/v#{version}/kx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "78daaa32c12acef454d6d66ed02aed8859f20c59e3c7d4a5471b1c25427e7b7a"
      url "https://github.com/eugene-panin/kx/releases/download/v#{version}/kx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8a0db1da34801f8b78eeded5225de84ea340b63bd1696782c60b061041d51ada"
      url "https://github.com/eugene-panin/kx/releases/download/v#{version}/kx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dd0f57f5ffde66cf01e2484aa692d5b34650407d02a96b7765d0a9cfd3a82464"
      url "https://github.com/eugene-panin/kx/releases/download/v#{version}/kx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kx"
  desc "Keep kubeconfigs for many clients' clusters in one place"
  homepage "https://github.com/eugene-panin/kx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kx"
  bash_completion "completions/kx.bash"
  fish_completion "completions/kx.fish"
  zsh_completion "completions/kx.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kx"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    kx builds ~/.kube/config from the clusters it manages.
    If that file already has clusters in it, start with: kx import-current
  EOS
end
