# This file was generated by GoReleaser. DO NOT EDIT.
cask "kx" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kx"]
    end
  end

  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "377cc868257b29dd24d6bc5cf03a8d757be2051ac2fca9cdf431144c39ae3539"
      url "https://github.com/eugene-panin/kx/releases/download/v#{version}/kx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b76df7edce4b64e0da58b3304ea9037292d0877a008fd9c8d7e578ab2f38c354"
      url "https://github.com/eugene-panin/kx/releases/download/v#{version}/kx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2b1137a022096e511385507846954d34b8f9f1a2854c6cca863632b77c02fc33"
      url "https://github.com/eugene-panin/kx/releases/download/v#{version}/kx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "adf570b98cdca05e5dd9ec6b896ba4b1e706895e0cba8a8f2a9a64ff45e220d1"
      url "https://github.com/eugene-panin/kx/releases/download/v#{version}/kx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kx"
  desc "Keep kubeconfigs for many clients' clusters in one place"
  homepage "https://github.com/eugene-panin/kx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kx"
  bash_completion "completions/kx.bash"
  fish_completion "completions/kx.fish"
  zsh_completion "completions/kx.zsh"

  # No zap stanza required

  caveats <<~EOS
    kx builds ~/.kube/config from the clusters it manages.
    If that file already has clusters in it, start with: kx import-current
  EOS
end
