# This file was generated by GoReleaser. DO NOT EDIT.
cask "kx" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "cc4aca01482483c8ba19794efb727b0448c634877a6c4b749e4c3853389d227b"
      url "https://github.com/eugene-panin/kx/releases/download/v#{version}/kx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5a8436e175e3bf4d03ad216441014803637931ae0ad975dbc7a2d10876d51740"
      url "https://github.com/eugene-panin/kx/releases/download/v#{version}/kx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2cea489b305a6d980c18debae1feef8687f220ade21873b2561f3189d5e5d603"
      url "https://github.com/eugene-panin/kx/releases/download/v#{version}/kx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "67a64eb6042529dd553740d6ccd40c4345fe7521a526a2d222ef7de9ebff7077"
      url "https://github.com/eugene-panin/kx/releases/download/v#{version}/kx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kx"
  desc "Keep kubeconfigs for many clients' clusters in one place"
  homepage "https://github.com/eugene-panin/kx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kx"
  bash_completion "completions/kx.bash"
  fish_completion "completions/kx.fish"
  zsh_completion "completions/kx.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kx"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    kx builds ~/.kube/config from the clusters it manages.
    If that file already has clusters in it, start with: kx import-current
  EOS
end
