# This file was generated by GoReleaser. DO NOT EDIT.
cask "vctx" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "a2552df6163d5e0f9d33527adb23235f879fc160d1b5b7fdf47776353c34b54d"
      url "https://github.com/eugene-panin/vctx/releases/download/v#{version}/vctx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d38671a22843e306e753798158d36d3a80a4a3db817bb256260d5c57475564a4"
      url "https://github.com/eugene-panin/vctx/releases/download/v#{version}/vctx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "719223489eb598b8793d429affc14c0d83e707d03f7fe6ee973e41e55ff608a4"
      url "https://github.com/eugene-panin/vctx/releases/download/v#{version}/vctx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "deefb3c783f106acc40746b34dbfc5b82dfdf8ef3fa5ed828559f61fb5fa8b09"
      url "https://github.com/eugene-panin/vctx/releases/download/v#{version}/vctx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vctx"
  desc "Switch the Vault CLI between several Vault instances"
  homepage "https://github.com/eugene-panin/vctx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vctx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vctx"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Put your Vault instances in ~/.config/vctx/config.yaml (format: vctx help),
    then run once: vctx init
  EOS
end
