# This file was generated by GoReleaser. DO NOT EDIT.
cask "vctx" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/vctx"]
    end
  end

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "6a4144a89853214545a749a89f8b0b5e3b1a1334fbb8a1535cb904e4aa423a8e"
      url "https://github.com/eugene-panin/vctx/releases/download/v#{version}/vctx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "97d1a82b716cb966fe34ca6ed2de23ec050d1d9195293048409db70911ecfbbe"
      url "https://github.com/eugene-panin/vctx/releases/download/v#{version}/vctx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "61173e3d9f28c11d40a9297693cb4bcb3a6154228a0a601af254b48db8a5f05d"
      url "https://github.com/eugene-panin/vctx/releases/download/v#{version}/vctx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e38905fa5cb94e0a6eea1c8f2ad91d29c9c865a2171603db0ba785e5a57d5f7f"
      url "https://github.com/eugene-panin/vctx/releases/download/v#{version}/vctx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vctx"
  desc "Switch the Vault CLI between several Vault instances"
  homepage "https://github.com/eugene-panin/vctx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vctx"

  # No zap stanza required

  caveats <<~EOS
    Put your Vault instances in ~/.config/vctx/config.yaml (format: vctx help),
    then run once: vctx init
  EOS
end
