# This file was generated by GoReleaser. DO NOT EDIT.
cask "vctx" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/vctx"]
    end
  end

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "3154b849dd7fdcc48879b04970701c78d58434d49123ab376e3f262cbbdcc085"
      url "https://github.com/eugene-panin/vctx/releases/download/v#{version}/vctx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "700f723f4fa62f1f325f1c51c7736e179a94a8fc362cecd5d6b14cd106389c59"
      url "https://github.com/eugene-panin/vctx/releases/download/v#{version}/vctx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a90c1ca02aa48e3a571aa6ca7e5e3b65e4d9c5800f062dcc400bdb70aa3ffcfd"
      url "https://github.com/eugene-panin/vctx/releases/download/v#{version}/vctx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "112c4acf526bdbcaeb5093182da94b531140aef0269a7e98221ec474b4eca7d6"
      url "https://github.com/eugene-panin/vctx/releases/download/v#{version}/vctx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vctx"
  desc "Switch the Vault CLI between several Vault instances"
  homepage "https://github.com/eugene-panin/vctx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vctx"
  bash_completion "completions/vctx.bash"
  fish_completion "completions/vctx.fish"
  zsh_completion "completions/vctx.zsh"

  # No zap stanza required

  caveats <<~EOS
    Put your Vault instances in ~/.config/vctx/config.yaml (format: vctx help),
    then run once: vctx init
  EOS
end
